version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.12.1-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=root
